### ISSUE TITLE
Backend recv functions does not implement recv all buffer.

### ISSUE THREAD

**Issue by victorpoluceno** [victorpoluceno/xwing#62]
The current recv function simply return content of one recv call, if the transmitted data is bigger than the configured buffer size, the data will be inconsistent and serialization will break.

Need to implement a recv function that receive data until a end of transmission by a termination mark. http://code.activestate.com/recipes/408859-socketrecv-three-ways-to-turn-it-into-recvall/

**Comment by mauricioabreu** [comment]
Could we use something like this? https://docs.python.org/3/library/asyncio-stream.html#asyncio-register-socket-streams

**Comment by victorpoluceno** [comment]
@mauricioabreu sure, it would be much easier, but I'm not sure about performance, look at this benchmark from uvloop guys: https://magic.io/blog/uvloop-blazing-fast-python-networking/

**Comment by victorpoluceno** [comment]
@mauricioabreu but I known that there is few performance improvements coming to asyncio soon, see this: 

https://github.com/python/asyncio/pull/339
https://github.com/python/asyncio/pull/385
https://github.com/python/asyncio/pull/395

May be we should use asyncio's Stream API and hope that its performance gets better. We can ways change that latter for something faster or even fix any performance problem on asyncio it self.
